"""Add financial intelligence tables

Revision ID: 89ee9532b883
Revises: b6c989ff64f7
Create Date: 2026-07-10 13:14:17.761661

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "89ee9532b883"
down_revision: str | Sequence[str] | None = "b6c989ff64f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recommendation_policies",
        sa.Column("policy_name", sa.String(length=100), nullable=False),
        sa.Column("policy_version", sa.String(length=32), nullable=False),
        sa.Column(
            "health_score_thresholds",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "max_severe_risks_allowed",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "requires_positive_growth",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "health_scores",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("fiscal_period", sa.String(length=10), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column(
            "category_scores",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "weights",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "score_explanation",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("percentile", sa.Float(), nullable=True),
        sa.Column("ratio_engine_version", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_health_scores_company_id"),
        "health_scores",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_scores_fiscal_period"),
        "health_scores",
        ["fiscal_period"],
        unique=False,
    )
    op.create_table(
        "ratios",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("fiscal_period", sa.String(length=10), nullable=False),
        sa.Column("ratio_name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.String(length=512), nullable=True),
        sa.Column("formula", sa.String(length=256), nullable=False),
        sa.Column(
            "line_items_used",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("ratio_engine_version", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ratios_company_id"), "ratios", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_ratios_fiscal_period"), "ratios", ["fiscal_period"], unique=False
    )
    op.create_index(
        op.f("ix_ratios_ratio_name"), "ratios", ["ratio_name"], unique=False
    )
    op.create_table(
        "recommendations",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("fiscal_period", sa.String(length=10), nullable=False),
        sa.Column("rating", sa.String(length=20), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column(
            "rules_applied",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "recommendation_policy_version", sa.String(length=32), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recommendations_company_id"),
        "recommendations",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendations_fiscal_period"),
        "recommendations",
        ["fiscal_period"],
        unique=False,
    )
    op.create_table(
        "risk_assessments",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("fiscal_period", sa.String(length=10), nullable=False),
        sa.Column("risk_category", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("supporting_evidence", sa.String(length=1024), nullable=False),
        sa.Column("ratio_engine_version", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_risk_assessments_company_id"),
        "risk_assessments",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_risk_assessments_fiscal_period"),
        "risk_assessments",
        ["fiscal_period"],
        unique=False,
    )
    op.create_table(
        "recommendation_histories",
        sa.Column("recommendation_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("fiscal_period", sa.String(length=10), nullable=False),
        sa.Column("rating", sa.String(length=20), nullable=False),
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("policy_version", sa.String(length=32), nullable=False),
        sa.Column("composite_score", sa.Float(), nullable=False),
        sa.Column(
            "reasoning_steps",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("triggered_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["recommendation_id"], ["recommendations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["triggered_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recommendation_histories_company_id"),
        "recommendation_histories",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendation_histories_fiscal_period"),
        "recommendation_histories",
        ["fiscal_period"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendation_histories_recommendation_id"),
        "recommendation_histories",
        ["recommendation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_recommendation_histories_recommendation_id"),
        table_name="recommendation_histories",
    )
    op.drop_index(
        op.f("ix_recommendation_histories_fiscal_period"),
        table_name="recommendation_histories",
    )
    op.drop_index(
        op.f("ix_recommendation_histories_company_id"),
        table_name="recommendation_histories",
    )
    op.drop_table("recommendation_histories")
    op.drop_index(
        op.f("ix_risk_assessments_fiscal_period"), table_name="risk_assessments"
    )
    op.drop_index(op.f("ix_risk_assessments_company_id"), table_name="risk_assessments")
    op.drop_table("risk_assessments")
    op.drop_index(
        op.f("ix_recommendations_fiscal_period"), table_name="recommendations"
    )
    op.drop_index(op.f("ix_recommendations_company_id"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_ratios_ratio_name"), table_name="ratios")
    op.drop_index(op.f("ix_ratios_fiscal_period"), table_name="ratios")
    op.drop_index(op.f("ix_ratios_company_id"), table_name="ratios")
    op.drop_table("ratios")
    op.drop_index(op.f("ix_health_scores_fiscal_period"), table_name="health_scores")
    op.drop_index(op.f("ix_health_scores_company_id"), table_name="health_scores")
    op.drop_table("health_scores")
    op.drop_table("recommendation_policies")
    # ### end Alembic commands ###
