"""
ExportService — exports a completed FinancialReport markdown to PDF and DOCX formats.
"""

import io
import logging
import re
from typing import Literal

logger = logging.getLogger("equityiq.application.report_export_service")

ExportFormat = Literal["markdown", "pdf", "docx"]


def _build_footer(
    report_template_version: str,
    financial_engine_version: str,
    recommendation_policy_version: str,
    rag_version: str,
    embedding_version: str,
    company_name: str,
    ticker: str,
    fiscal_period: str,
    generated_at: str,
    workspace_name: str,
) -> str:
    """Build the standardized export footer string."""
    return (
        f"Generated by EquityIQ | Report v{report_template_version} | "
        f"FI Version: {financial_engine_version} | "
        f"Recommendation Policy: {recommendation_policy_version} | "
        f"RAG Version: {rag_version} | "
        f"Embeddings: {embedding_version} | "
        f"Generated at: {generated_at} UTC | "
        f"Workspace: {workspace_name} | "
        f"Company: {company_name} ({ticker}) | "
        f"Period: {fiscal_period}"
    )


class ExportService:
    """
    Handles export of completed report markdown content to multiple output formats.

    Supported formats:
    - Markdown (raw text passthrough)
    - PDF (via WeasyPrint HTML rendering)
    - DOCX (via python-docx)

    PDF and DOCX generation gracefully degrade to plaintext if dependencies
    are not installed (allows the system to run without optional PDF/DOCX libs).
    """

    def export_markdown(self, content: str) -> bytes:
        """
        Return raw markdown content as UTF-8 bytes.
        """
        return content.encode("utf-8")

    def export_pdf(
        self,
        content: str,
        footer_text: str,
        title: str = "EquityIQ Financial Report",
    ) -> bytes:
        """
        Convert markdown content to a styled PDF using WeasyPrint.

        Falls back to plain text PDF if WeasyPrint is unavailable.
        """
        try:
            from weasyprint import HTML

            html_content = self._markdown_to_html(content, title, footer_text)
            pdf_bytes: bytes = HTML(string=html_content).write_pdf()
            return pdf_bytes
        except ImportError:
            logger.warning(
                "WeasyPrint not installed. Falling back to plain text PDF export."
            )
            return self._plaintext_pdf_fallback(content, footer_text)

    def export_docx(
        self,
        content: str,
        footer_text: str,
        title: str = "EquityIQ Financial Report",
    ) -> bytes:
        """
        Convert markdown content to a DOCX document using python-docx.

        Falls back to plain UTF-8 bytes if python-docx is unavailable.
        """
        try:
            from docx import Document
            from docx.shared import Pt

            document = Document()

            # Set document title
            document.add_heading(title, level=0)

            # Parse and add content line by line
            for line in content.splitlines():
                if line.startswith("# "):
                    document.add_heading(line[2:].strip(), level=1)
                elif line.startswith("## "):
                    document.add_heading(line[3:].strip(), level=2)
                elif line.startswith("### "):
                    document.add_heading(line[4:].strip(), level=3)
                elif line.startswith("#### "):
                    document.add_heading(line[5:].strip(), level=4)
                elif line.startswith("|"):
                    # Tables — add as paragraphs (simplified)
                    para = document.add_paragraph(line)
                    para.style = document.styles["Normal"]
                elif line.startswith("> "):
                    document.add_paragraph(line[2:].strip(), style="Quote")
                elif line.strip() == "---":
                    document.add_paragraph("─" * 60)
                elif line.strip():
                    document.add_paragraph(line.strip())

            # Add footer as a separate paragraph
            document.add_paragraph()
            footer_para = document.add_paragraph(footer_text)
            if footer_para.runs:
                footer_para.runs[0].font.size = Pt(8)

            # Serialize to bytes
            buffer = io.BytesIO()
            document.save(buffer)
            return buffer.getvalue()

        except ImportError:
            logger.warning(
                "python-docx not installed. Falling back to plain text export."
            )
            return (content + "\n\n" + footer_text).encode("utf-8")

    def _markdown_to_html(self, content: str, title: str, footer_text: str) -> str:
        """Convert markdown content to HTML with CSS styling for WeasyPrint."""
        # Simple regex-based markdown → HTML conversion
        lines: list[str] = []
        for line in content.splitlines():
            if line.startswith("#### "):
                lines.append(f"<h4>{self._escape_html(line[5:].strip())}</h4>")
            elif line.startswith("### "):
                lines.append(f"<h3>{self._escape_html(line[4:].strip())}</h3>")
            elif line.startswith("## "):
                lines.append(f"<h2>{self._escape_html(line[3:].strip())}</h2>")
            elif line.startswith("# "):
                lines.append(f"<h1>{self._escape_html(line[2:].strip())}</h1>")
            elif line.startswith("> "):
                lines.append(
                    f"<blockquote>{self._escape_html(line[2:].strip())}</blockquote>"
                )
            elif line.startswith("---"):
                lines.append("<hr/>")
            elif line.strip():
                # Inline formatting
                formatted = self._inline_format(line)
                lines.append(f"<p>{formatted}</p>")
            else:
                lines.append("<br/>")

        body_html = "\n".join(lines)

        css = """
            @page {
                margin: 2cm;
                @bottom-center {
                    content: string(footer);
                    font-size: 8pt;
                    color: #666;
                }
            }
            body { font-family: Arial, sans-serif; font-size: 11pt; line-height: 1.5; }
            h1 { color: #1a1a2e; border-bottom: 2px solid #1a1a2e; }
            h2 { color: #16213e; margin-top: 1.5em; }
            h3 { color: #0f3460; }
            blockquote { border-left: 4px solid #e94560; padding-left: 1em; color: #444; }
            hr { border: 0; border-top: 1px solid #ccc; }
            .footer { font-size: 8pt; color: #666; border-top: 1px solid #ccc; margin-top: 2em; }
        """

        return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>{self._escape_html(title)}</title>
<style>{css}</style>
</head>
<body>
{body_html}
<div class="footer">{self._escape_html(footer_text)}</div>
</body>
</html>"""

    @staticmethod
    def _escape_html(text: str) -> str:
        return (
            text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
        )

    @staticmethod
    def _inline_format(text: str) -> str:
        """Apply basic inline markdown formatting (bold, italic, code)."""
        # Bold: **text**
        text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
        # Italic: *text* or _text_
        text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
        # Code: `text`
        text = re.sub(r"`(.+?)`", r"<code>\1</code>", text)
        return text

    def _plaintext_pdf_fallback(self, content: str, footer_text: str) -> bytes:
        """Plain text fallback when WeasyPrint is unavailable."""
        return (content + "\n\n" + footer_text).encode("utf-8")
