"""
ResponseValidator application service.
"""

import logging
import re

from app.application.services.context_assembler import MergedContextChunk
from app.domain.exceptions import ResponseValidationError

logger = logging.getLogger("equityiq.application.response_validator")


class ResponseValidator:
    """
    Validates LLM-generated responses for factual grounding, strict citation mapping,
    and numerical consistency against the retrieved chunks context.
    """

    def __init__(self) -> None:
        # Regex to find citations in format [Chunk X]
        self.citation_pattern = re.compile(r"\[Chunk\s+(\d+)\]", re.IGNORECASE)
        # Regex to match numeric figures (currency, decimal percentage, etc.)
        self.number_pattern = re.compile(
            r"\$?\b\d+(?:\.\d+)?\s*(?:billion|million|B|M|%)?\b", re.IGNORECASE
        )

    def validate_response(
        self, response_text: str, merged_chunks: list[MergedContextChunk]
    ) -> None:
        """
        Runs comprehensive validation. Raises ResponseValidationError on failure.
        """
        if not response_text:
            raise ResponseValidationError("Empty response generated by LLM.")

        # 1. Parse citation anchors
        matches = self.citation_pattern.findall(response_text)
        cited_indexes = [int(m) for m in matches]

        # Check for dangling chunk references
        max_valid_index = len(merged_chunks)
        for idx in cited_indexes:
            if idx < 1 or idx > max_valid_index:
                logger.warning(
                    f"Dangling citation index found: [Chunk {idx}] (Max allowed: {max_valid_index})"
                )
                raise ResponseValidationError(
                    f"Validation Failure: Dangling citation reference '[Chunk {idx}]' does not exist."
                )

        # 2. Split response text into sentences to audit localized numerical grounding
        sentences = [
            s.strip() for s in re.split(r"(?<=[.!?])\s+", response_text) if s.strip()
        ]

        for sentence in sentences:
            # Find numbers in this sentence
            numbers = self.number_pattern.findall(sentence)
            if not numbers:
                continue

            # Find citations in this sentence
            sentence_citations = self.citation_pattern.findall(sentence)
            sentence_indexes = [int(m) for m in sentence_citations]

            # Filter out small integers (0-20) to avoid false positives on list items, etc.
            meaningful_numbers = []
            for num in numbers:
                clean_num = num.replace("$", "").replace("%", "").strip()
                try:
                    val = float(clean_num)
                    if val.is_integer() and 0 <= val <= 20:
                        continue
                except ValueError:
                    pass
                meaningful_numbers.append(num)

            if not meaningful_numbers:
                continue

            # Metric is present but sentence lacks citation anchors
            if not sentence_indexes:
                logger.warning(
                    "Unsupported claim detected. Sentence contains metrics but no citations: "
                    f"'{sentence}'"
                )
                raise ResponseValidationError(
                    "Validation Failure: Response contains financial metrics without corresponding grounding citations."
                )

            # Check that the numbers exist in the text of the cited chunks
            for num in meaningful_numbers:
                num_found = False
                clean_num_pattern = num.replace("$", "").replace("%", "").strip()

                for index in sentence_indexes:
                    target_chunk = merged_chunks[index - 1]
                    if (
                        clean_num_pattern.lower() in target_chunk.content.lower()
                        or num.lower() in target_chunk.content.lower()
                    ):
                        num_found = True
                        break

                if not num_found:
                    logger.warning(
                        f"Numerical consistency failed. Number '{num}' in sentence "
                        f"citing {[f'[Chunk {i}]' for i in sentence_indexes]} was not found in cited context."
                    )
                    raise ResponseValidationError(
                        f"Validation Failure: Number '{num}' could not be verified in cited chunks."
                    )

        logger.info(
            "Response grounding and numerical validation completed successfully."
        )
